networks:
  my-net:
    driver: bridge

services:
  spring-app:
    image: ${DOCKER_USERNAME}/myspringapp
    container_name: paw-backend
    networks:
      - my-net
    depends_on:
      redis-server:
        condition: service_healthy
  redis-server:
    image: redis
    container_name: paw-redis
    networks:
      - my-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
  nginx:
    image: ${DOCKER_USERNAME}/mynginx
    container_name: paw-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - my-net
    depends_on:
      - spring-app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # 호스트의 /etc/letsencrypt와 컨테이너의 /etc/letsencrypt를 연동
    user: "1000:1000" # 상기 파일 권한 부여된 사용자로 uid:gid 설정
