name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  # build(test포함) 진행
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean build

  close_pr:
    runs-on: ubuntu-latest
    needs: build
    if: failure  # build(test포함) 실패시 pr 닫기
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Close PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --base develop --json number --jq '.[0].number')
          if [[ -n "$PR_NUMBER" ]]; then
            gh pr close "$PR_NUMBER" --comment "PR is being closed as part of CI pipeline."
          else
            echo "No open PRs to close."
          fi
